POST http://localhost:3000/api/temples

Content-Type: application/json

{
    "name": "Templo de Campinas",
  "address": "Rua James Esdras Faust, 400 Bairro Notre Dame CEP 13092-820 Campinas - SP, Brazil,",
  "telephone": "(55) 19-2102-5800",
  "photoUrl": "https://assets.churchofjesuschrist.org/33/cb/33cb73d045a401cfc3d837910eac29ab672ae74c/campinas_brazil_temple_lds.jpeg"
}

###

GET http://localhost:3000/api/temples